services :
  jupyterlab:
    build:
      context : .
      dockerfile: Dockerfile
    image : myj:1.0
    container_name : jupyterlab
    hostname: JUPYTERLAB
    command: /bin/bash -c "service ssh start && python3 -m jupyterlab --ip=0.0.0.0 --port=8888 --allow-root --FileContentsManager.delete_to_trash=False"
    ports:
      - '8888:8888' # 기본 주피터랩 웹포트 8888
      - '22:22' #ssh 기본포트 
    
